# Training metadata
seed: 1
torch_deterministic: True
cuda: True
track: False
wandb_project_name: "Darl"
wandb_entity: ""
capture_video: False

exp_name: 'test'
env_id: "MiniGrid-Empty-8x8-v0"
total_timesteps: 100_000
buffer_size: 100_000
gamma: 0.99
tau: 0.005
batch_size: 256
learning_starts: 5e3
policy_lr: 1e-4
q_lr: 1e-4
update_frequency: 2
target_network_frequency: 8000
alpha: 0.2
autotune: True
target_entropy_scale: 0.98
n_envs: 1