defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 2137
      consider_magic_clip: true
    direction: maximize
    study_name: minigrid
    storage: null
    n_trials: 100
    n_jobs: 1
    max_failure_rate: 0.0
    params:
      optim.q_lr: range(1e-4, 1e-3, 1e-4)
      optim.alpha_lr: range(1e-4, 1e-3, 1e-4)
      sac.alpha: range(0.2, 0.6, 0.1)
      sac.target_entropy_scale: choice(0.82, 0.89, 0.98)
      sac.tau: range(5e-3, 5e-2, 1e-3)
      env.grayscale: choice(False, True)
      env.frame_stack: choice(1, 3)

# Training metadata
meta:
  exp_name: 'test'
  seed: 1
  torch_deterministic: True
  cuda: True
  track: False
  wandb_project_name: "Darl"
  wandb_entity: ""

critic:
  hidden_features: 1024

encoder:
  img_size: 100
  num_filters: 32
  out_features: 50
  crop: True

env:
  id: "MiniGrid-Empty-8x8-v0"
  # id: "MiniGrid-FourRooms-v0"
  frame_stack: 1
  grayscale: True
  capture_video: False

train:
  total_timesteps: 100_000
  buffer_size: 100_000
  n_envs: 1
  batch_size: 256

dqn:
  start_eps: 1
  end_eps: 0.01
  exploration_fraction: 0.2
  learning_starts: 1e4
  train_frequency: 1
  gamma: 0.99
  target_network_frequency: 1
  tau: 0.005
  # tau: 1.0
  # tau: 0.095

optim:
  q_lr: 5e-4
