defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 2137
      consider_magic_clip: true
    direction: maximize
    study_name: minigrid
    storage: null
    n_trials: 100
    n_jobs: 1
    max_failure_rate: 0.0
    params:
      optim.q_lr: range(1e-4, 1e-3, 1e-4)
      dqn.exploration_fraction: range(1e-1, 3e-1, 1e-1)
      dqn.end_eps: choice(0.05, 0.1, 0.2)
      dqn.train_frequency: choice(1, 2, 4)
      dqn.target_network_frequency: choice(1, 4, 100, 2000)
      dqn.tau: range(0.005, 1.0, 0.01)


# Training metadata
meta:
  exp_name: 'test'
  seed: 1
  torch_deterministic: True
  cuda: True
  track: False
  wandb_project_name: "Darl"
  wandb_entity: ""

qnetwork:
  num_features : 1024

encoder:
  img_size: 84
  num_filters: 32
  out_features: 50
  crop: True

env:
  # id: "MiniGrid-Empty-8x8-v0"
  id: "MiniGrid-Unlock-v0"
  # id: "MiniGrid-FourRooms-v0"
  frame_stack: 1
  grayscale: True
  capture_video: False

train:
  total_timesteps: 500_000
  buffer_size: 100_000
  n_envs: 1
  batch_size: 256

dqn:
  gamma: 0.99
  start_eps: 1
  end_eps: 0.2
  exploration_fraction: 0.2
  learning_starts: 1e4
  train_frequency: 1
  target_network_frequency: 100
  tau: 0.0275
  # target_network_frequency: 1000
  # tau: 0.001

optim:
  q_lr: 2e-4
